swagger: "2.0"
info:
  title: An api for users
  description: This api manages users with CRUD operations
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/user:
    get:
      tags:
      - user
      summary: show user
      operationId: user#show
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserUserManagementResponseCollection'
      schemes:
      - http
  /api/v1/user/{ID}:
    get:
      tags:
      - user
      summary: get user
      operationId: user#get
      parameters:
      - name: ID
        in: path
        description: ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserGetResponseBody'
      schemes:
      - http
    post:
      tags:
      - user
      summary: add user
      operationId: user#add
      parameters:
      - name: ID
        in: path
        description: ID
        required: true
        type: string
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserAddRequestBody'
          required:
          - UserName
      responses:
        "201":
          description: Created response.
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - user
      summary: Download ./gen/http/openapi.json
      operationId: user#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  UserAddRequestBody:
    title: UserAddRequestBody
    type: object
    properties:
      UserName:
        type: string
        description: User Name
        example: Molestiae ex.
    example:
      UserName: Nemo esse minus rem.
    required:
    - UserName
  UserGetResponseBody:
    title: 'Mediatype identifier: application/vnd.user; view=default'
    type: object
    properties:
      ID:
        type: string
        description: ID is the unique id of the User.
        example: "1"
      UserName:
        type: string
        description: Name of the User
        example: Rakesh Mothukuri
    description: GetResponseBody result type (default view)
    example:
      ID: "1"
      UserName: Rakesh Mothukuri
    required:
    - ID
    - UserName
  UserManagementResponse:
    title: 'Mediatype identifier: application/vnd.user; view=default'
    type: object
    properties:
      ID:
        type: string
        description: ID is the unique id of the User.
        example: "1"
      UserName:
        type: string
        description: Name of the User
        example: Rakesh Mothukuri
    description: A UserManagement type describes a User of e-store. (default view)
    example:
      ID: "1"
      UserName: Rakesh Mothukuri
    required:
    - ID
    - UserName
  UserUserManagementResponseCollection:
    title: 'Mediatype identifier: application/vnd.user; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/UserManagementResponse'
    description: ShowResponseBody is the result type for an array of UserManagementResponse (default view)
    example:
    - ID: "1"
      UserName: Rakesh Mothukuri
    - ID: "1"
      UserName: Rakesh Mothukuri
