swagger: "2.0"
info:
  title: An api for fruit shop online purchases
  description: This api manages online fruit shop with CRUD operations
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/cart/{cartId}:
    get:
      tags:
      - cart
      summary: get cart
      operationId: cart#get
      parameters:
      - name: cartId
        in: path
        description: cartId
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CartCartManagementResponseCollection'
      schemes:
      - http
  /api/v1/cart/add/{cartId}:
    post:
      tags:
      - cart
      summary: add cart
      operationId: cart#add
      parameters:
      - name: cartId
        in: path
        description: cartId of the user
        required: true
        type: string
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/CartAddRequestBody'
          required:
          - Name
          - Count
      responses:
        "202":
          description: Accepted response.
      schemes:
      - http
  /api/v1/cart/remove/{cartId}:
    post:
      tags:
      - cart
      summary: remove cart
      operationId: cart#remove
      parameters:
      - name: cartId
        in: path
        description: cartId of the user
        required: true
        type: string
      - name: RemoveRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/CartRemoveRequestBody'
          required:
          - Name
          - Count
      responses:
        "202":
          description: Accepted response.
      schemes:
      - http
  /api/v1/fruit:
    get:
      tags:
      - fruit
      summary: show fruit
      operationId: fruit#show
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/FruitFruitManagementResponseCollection'
      schemes:
      - http
  /api/v1/fruit/{Name}:
    get:
      tags:
      - fruit
      summary: get fruit
      operationId: fruit#get
      parameters:
      - name: Name
        in: path
        description: Name
        required: true
        type: string
      - name: GetRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/FruitGetRequestBody'
          required:
          - Cost
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/FruitGetResponseBody'
      schemes:
      - http
  /api/v1/payment/{ID}/{cartId}:
    get:
      tags:
      - payment
      summary: get payment
      operationId: payment#get
      parameters:
      - name: ID
        in: path
        description: cartId
        required: true
        type: string
      - name: cartId
        in: path
        description: cartId
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PaymentGetResponseBody'
      schemes:
      - http
  /api/v1/payment/pay/{ID}:
    post:
      tags:
      - payment
      summary: add payment
      operationId: payment#add
      parameters:
      - name: ID
        in: path
        description: ID of the user
        required: true
        type: string
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PaymentAddRequestBody'
          required:
          - cartId
          - Amount
      responses:
        "202":
          description: Accepted response.
          schema:
            $ref: '#/definitions/PaymentAddResponseBody'
      schemes:
      - http
  /api/v1/user:
    get:
      tags:
      - user
      summary: show user
      operationId: user#show
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserUserManagementResponseCollection'
      schemes:
      - http
  /api/v1/user/{ID}:
    get:
      tags:
      - user
      summary: get user
      operationId: user#get
      parameters:
      - name: ID
        in: path
        description: ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserGetResponseBody'
      schemes:
      - http
    post:
      tags:
      - user
      summary: add user
      operationId: user#add
      parameters:
      - name: ID
        in: path
        description: ID
        required: true
        type: string
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserAddRequestBody'
          required:
          - UserName
      responses:
        "201":
          description: Created response.
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - user
      summary: Download ./gen/http/openapi.json
      operationId: user#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  CartAddRequestBody:
    title: CartAddRequestBody
    type: object
    properties:
      CostPerItem:
        type: number
        description: Cost of fruits
        example: 0.47037292765073974
        format: double
      Count:
        type: integer
        description: Number of fruits
        example: 4411944650868754131
        format: int64
      Name:
        type: string
        description: Name of the fruit
        example: Nam nemo aliquid ipsa nostrum qui.
      TotalCost:
        type: number
        description: Total cost for the item
        example: 0.9163754415571708
        format: double
    example:
      CostPerItem: 0.2876743323246392
      Count: 578118207626934877
      Name: Accusamus eos odio autem quidem voluptatem ratione.
      TotalCost: 0.40068066636823596
    required:
    - Name
    - Count
  CartCartManagementResponseCollection:
    title: 'Mediatype identifier: application/vnd.cart; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/CartManagementResponse'
    description: GetResponseBody is the result type for an array of CartManagementResponse (default view)
    example:
    - CostPerItem: 2
      Count: 2
      Name: Apple
      TotalCost: 4
      cartId: "1"
    - CostPerItem: 2
      Count: 2
      Name: Apple
      TotalCost: 4
      cartId: "1"
  CartManagementResponse:
    title: 'Mediatype identifier: application/vnd.cart; view=default'
    type: object
    properties:
      CostPerItem:
        type: number
        description: Cost of Each fruit
        example: 2
        format: double
      Count:
        type: integer
        description: Number of fruits
        example: 2
        format: int64
      Name:
        type: string
        description: Name of the fruit
        example: Apple
      TotalCost:
        type: number
        description: Total cost of fruits
        example: 4
        format: double
      cartId:
        type: string
        description: cartId is the unique id of the User.
        example: "1"
    description: A CartManagement type describes users cart state. (default view)
    example:
      CostPerItem: 2
      Count: 2
      Name: Apple
      TotalCost: 4
      cartId: "1"
    required:
    - cartId
    - Name
    - Count
    - CostPerItem
    - TotalCost
  CartRemoveRequestBody:
    title: CartRemoveRequestBody
    type: object
    properties:
      CostPerItem:
        type: number
        description: Cost of fruits
        example: 0.04467929195032163
        format: double
      Count:
        type: integer
        description: Number of fruits
        example: 4971639452633052563
        format: int64
      Name:
        type: string
        description: Name of the fruit
        example: Aut vitae.
      TotalCost:
        type: number
        description: Total cost for the item
        example: 0.32287398640890763
        format: double
    example:
      CostPerItem: 0.09290485256542964
      Count: 8072899782453271251
      Name: Id et veritatis delectus consequatur quasi temporibus.
      TotalCost: 0.5439296629364719
    required:
    - Name
    - Count
  FruitFruitManagementResponseCollection:
    title: 'Mediatype identifier: application/vnd.fruit; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/FruitManagementResponse'
    description: ShowResponseBody is the result type for an array of FruitManagementResponse (default view)
    example:
    - Cost: 1
      Name: Apple
    - Cost: 1
      Name: Apple
  FruitGetRequestBody:
    title: FruitGetRequestBody
    type: object
    properties:
      Cost:
        type: number
        description: Cost
        example: 0.8515266289951227
        format: double
    example:
      Cost: 0.2753206776558638
    required:
    - Cost
  FruitGetResponseBody:
    title: 'Mediatype identifier: application/vnd.fruit; view=default'
    type: object
    properties:
      Cost:
        type: number
        description: Cost of the Fruit.
        example: 1
        format: double
      Name:
        type: string
        description: Name is the unique Name of the Fruit.
        example: Apple
    description: GetResponseBody result type (default view)
    example:
      Cost: 1
      Name: Apple
    required:
    - Name
    - Cost
  FruitManagementResponse:
    title: 'Mediatype identifier: application/vnd.fruit; view=default'
    type: object
    properties:
      Cost:
        type: number
        description: Cost of the Fruit.
        example: 1
        format: double
      Name:
        type: string
        description: Name is the unique Name of the Fruit.
        example: Apple
    description: A FruitManagement type describes a Fruit of e-store. (default view)
    example:
      Cost: 1
      Name: Apple
    required:
    - Name
    - Cost
  PaymentAddRequestBody:
    title: PaymentAddRequestBody
    type: object
    properties:
      Amount:
        type: number
        description: Total cost of the cart
        example: 0.48801406869022196
        format: double
      cartId:
        type: string
        description: cartId of the user
        example: Architecto eos facilis.
    example:
      Amount: 0.04155343685935064
      cartId: Enim consectetur dolor dolor dolorum.
    required:
    - cartId
    - Amount
  PaymentAddResponseBody:
    title: 'Mediatype identifier: application/vnd.payment; view=default'
    type: object
    properties:
      Amount:
        type: number
        description: Amount to be paid for the purchase
        example: 50
        format: double
      ID:
        type: string
        description: cartId is the unique cart id of the User.
        example: "1"
      PaymentStatus:
        type: string
        description: Payment status
        example: Success
      cartId:
        type: string
        description: cartId is the unique cart id of the User.
        example: "1"
    description: AddResponseBody result type (default view)
    example:
      Amount: 50
      ID: "1"
      PaymentStatus: Success
      cartId: "1"
    required:
    - cartId
  PaymentGetResponseBody:
    title: 'Mediatype identifier: application/vnd.payment; view=default'
    type: object
    properties:
      Amount:
        type: number
        description: Amount to be paid for the purchase
        example: 50
        format: double
      ID:
        type: string
        description: cartId is the unique cart id of the User.
        example: "1"
      PaymentStatus:
        type: string
        description: Payment status
        example: Success
      cartId:
        type: string
        description: cartId is the unique cart id of the User.
        example: "1"
    description: GetResponseBody result type (default view)
    example:
      Amount: 50
      ID: "1"
      PaymentStatus: Success
      cartId: "1"
    required:
    - cartId
  UserAddRequestBody:
    title: UserAddRequestBody
    type: object
    properties:
      UserName:
        type: string
        description: User Name
        example: Sit nesciunt cumque et provident eaque est.
    example:
      UserName: A iure et autem excepturi.
    required:
    - UserName
  UserGetResponseBody:
    title: 'Mediatype identifier: application/vnd.user; view=default'
    type: object
    properties:
      ID:
        type: string
        description: ID is the unique id of the User.
        example: "1"
      UserName:
        type: string
        description: Name of the User
        example: Rakesh Mothukuri
    description: GetResponseBody result type (default view)
    example:
      ID: "1"
      UserName: Rakesh Mothukuri
    required:
    - ID
    - UserName
  UserManagementResponse:
    title: 'Mediatype identifier: application/vnd.user; view=default'
    type: object
    properties:
      ID:
        type: string
        description: ID is the unique id of the User.
        example: "1"
      UserName:
        type: string
        description: Name of the User
        example: Rakesh Mothukuri
    description: A UserManagement type describes a User of e-store. (default view)
    example:
      ID: "1"
      UserName: Rakesh Mothukuri
    required:
    - ID
    - UserName
  UserUserManagementResponseCollection:
    title: 'Mediatype identifier: application/vnd.user; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/UserManagementResponse'
    description: ShowResponseBody is the result type for an array of UserManagementResponse (default view)
    example:
    - ID: "1"
      UserName: Rakesh Mothukuri
    - ID: "1"
      UserName: Rakesh Mothukuri
    - ID: "1"
      UserName: Rakesh Mothukuri
    - ID: "1"
      UserName: Rakesh Mothukuri
